export const solutions = [
  { number: '01', title: 'Consultoria e Suporte', short: 'Manutenção preventiva e corretiva, administração e monitoramento da sua infraestrutura de TI.', detail: 'Esse serviço tem como finalidade a manutenção preventiva e corretiva, administração, gerenciamento, controle e monitoramento de infraestrutura de servidores, sistemas e soluções de rede.', points: ['Manutenção preventiva e corretiva', 'Administração de servidores e sistemas', 'Monitoramento da infraestrutura'] },
  { number: '02', title: 'Segurança da Informação', short: 'Proteção de ponta a ponta para ajudar a evitar vazamentos de dados e infecções.', detail: 'Ajudamos a proteger a sua empresa de ponta a ponta, evitando os prejuízos causados por vazamento de dados ou infecções.', points: ['Segurança Endpoint com Bitdefender', 'Segurança da Internet com Fortinet', 'Controle de aplicações e políticas baseadas em identidade'] },
  { number: '03', title: 'Soluções de Backup Gerenciado', short: 'Proteção de dados com soluções de hardware e software, incluindo tecnologia Veeam.', detail: 'Trabalhamos com soluções de hardware e software para sistemas de backup. Uma tecnologia utilizada pela nossa equipe é a Veeam, que reúne facilidade de uso e recursos para organizações de diferentes tamanhos.', points: ['Soluções de hardware e software', 'Tecnologia Veeam', 'Proteção de dados para empresas'] },
  { number: '04', title: 'Equipamentos Dell', short: 'Storage, servidores, desktops e notebooks adequados às necessidades da sua empresa.', detail: 'Como parceiros Dell, temos conhecimento para oferecer o equipamento mais adequado para você ou sua empresa. Os equipamentos Dell entregam qualidade em seus materiais e acabamento.', points: ['Storage', 'Servidores', 'Desktops e notebooks'] },
  { number: '05', title: 'Infraestrutura de Redes', short: 'Soluções para as camadas física e lógica da rede da sua operação.', detail: 'Nossa infraestrutura de serviços de rede está dividida em duas áreas distintas: física e lógica. Trabalhamos com cabeamento, conectividade, integração e monitoramento de redes.', points: ['Rede física e cabeamento', 'Rede lógica e integração', 'Monitoramento LAN, WAN e Wi-Fi'] },
  { number: '06', title: 'Licenciamento', short: 'Orientação para licenciar os softwares que sua empresa utiliza.', detail: 'Possuímos uma equipe capacitada e sempre disposta a ajudar no seu licenciamento. Trabalhamos com Microsoft, Bitdefender, Arcserve, Veeam, Adobe e Corel.', points: ['Microsoft e Adobe', 'Bitdefender, Arcserve e Veeam', 'Corel e outras soluções'] },
];

export const news = [
  { title: 'O que contempla o serviço de Consultoria e Suporte em TI?', date: '12 maio 2022', category: 'Consultoria', excerpt: 'Os principais benefícios da manutenção preventiva e corretiva e do monitoramento de servidores.', url: 'https://d2c.net.br/2022/05/12/o-que-contempla-o-servico-de-consultoria-e-suporte-em-ti/' },
  { title: 'Você sabe o que é Inteligência Artificial?', date: 'Novidades', category: 'Tecnologia', excerpt: 'Uma introdução à inteligência artificial e ao seu papel no mundo dos negócios.', url: 'https://d2c.net.br/novidades/' },
  { title: 'Como o Machine Learning pode te ajudar no seu negócio?', date: 'Novidades', category: 'Tecnologia', excerpt: 'Conheça aplicações de aprendizado de máquina no dia a dia das empresas.', url: 'https://d2c.net.br/novidades/' },
  { title: 'Licenciamento de software sem dor de cabeça é na Dualcon', date: '11 fevereiro 2022', category: 'Licenciamento', excerpt: 'O licenciamento não precisa tomar o tempo que você dedica ao crescimento do negócio.', url: 'https://d2c.net.br/2022/02/11/licenciamento-de-software-sem-dor-de-cabeca-e-na-dualcon/' },
  { title: 'Segurança Cibernética', date: '03 fevereiro 2022', category: 'Segurança', excerpt: 'Por que a prevenção ajuda a reduzir o risco e o impacto dos ataques cibernéticos.', url: 'https://d2c.net.br/2022/02/03/seguranca-cibernetica/' },
  { title: 'Suporte Técnico preventivo', date: '14 julho 2021', category: 'Consultoria', excerpt: 'Um olhar preventivo para reduzir problemas com servidores e infraestrutura.', url: 'https://d2c.net.br/2021/07/14/suporte-tecnico-preventivo/' },
];
